name: Build OpenWRT
on:
  push:
    branches:
      - masterjobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Environment
      run: sudo apt-get update && sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python
      
    - name: Compile OpenWRT
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make menuconfig
        make
          
